name: Main

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:

  integration-tests:
    uses: ./.github/workflows/integration_tests.yaml

  publish:
    if: github.ref_name == 'main'
    needs: integration-tests
    uses: ./.github/workflows/publish.yaml
